name: Reusable Python CI/CD

on:
  workflow_call:
    inputs:
      python_version:
        description: Python Version
        required: true
        type: string

      image_name:
        description: Docker Image Name
        required: true
        type: string

    secrets:
      SONAR_TOKEN:
        required: true

      DOCKER_USERNAME:
        required: true

      DOCKER_PASSWORD:
        required: true

      EC2_HOST:
        required: true

      EC2_USERNAME:
        required: true

      EC2_SSH_KEY:
        required: true

jobs:
  build-test-deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python_version }}

      - name: Verify Docker
        run: |
          docker --version

      - name: Install Requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Verify Application Import
        run: |
          python -c "from app import app"

      - name: Run Unit Tests
        run: |
          python -m pytest tests \
            --cov=. \
            --cov-report=xml \
            -v

      - name: Remove Python Cache
        run: |
          find . -type d -name "__pycache__" -exec rm -rf {} +
          find . -type f -name "*.pyc" -delete

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build \
            -t ${{ secrets.DOCKER_USERNAME }}/${{ inputs.image_name }}:${{ github.sha }} .

      - name: Push Docker Image
        run: |
          docker push \
            ${{ secrets.DOCKER_USERNAME }}/${{ inputs.image_name }}:${{ github.sha }}

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            set -e

            IMAGE=${{ secrets.DOCKER_USERNAME }}/${{ inputs.image_name }}:${{ github.sha }}

            echo "===== Checking Docker ====="

            if ! command -v docker >/dev/null 2>&1; then

              if command -v yum >/dev/null 2>&1; then
                sudo yum install -y docker
              else
                sudo apt-get update
                sudo apt-get install -y docker.io
              fi

              sudo systemctl enable docker
              sudo systemctl start docker

            fi

            docker --version

            echo "===== Docker Login ====="

            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login \
              -u "${{ secrets.DOCKER_USERNAME }}" \
              --password-stdin

            echo "===== Pull Image ====="

            docker pull $IMAGE

            echo "===== Remove Old Temp Container ====="

            docker stop python-temp || true
            docker rm python-temp || true

            echo "===== Start Temporary Container ====="

            docker run -d \
              --name python-temp \
              -p 5001:5000 \
              $IMAGE

            echo "Waiting..."

            sleep 15

            echo "===== Health Check ====="

            if curl --fail http://localhost:5001/health
            then

              echo "Health Check Passed"

              docker stop python-flask-app || true
              docker rm python-flask-app || true

              docker run -d \
                --name python-flask-app \
                --restart always \
                -p 5000:5000 \
                $IMAGE

              docker stop python-temp
              docker rm python-temp

              echo "Deployment Successful"

            else

              echo "Deployment Failed"

              docker logs python-temp

              docker stop python-temp || true
              docker rm python-temp || true

              exit 1

            fi